//idk how to make this more compact
require("blocks/generator/adv-steam");
require("blocks/generator/therm");
require("blocks/generator/clicker-gen");
require("blocks/generator/reactor")
require("blocks/turret/cross-bow");
require("blocks/turret/salt-gun");
require("blocks/turret/silo");
require("blocks/turret/dome-silo");
require("blocks/turret/minigun");
require("blocks/crafter/spore-havester");
require("blocks/crafter/big-phase");
require("blocks/crafter/lab");
require("blocks/defense/shootWall")
require("blocks/distribution/big-router")
require("blocks/distribution/conjoiner")
require("blocks/distribution/phase-bridge")
require("blocks/drill/phase-drill")
require("blocks/drill/gear-drill")
require("blocks/misc/collector")
require("blocks/misc/cooler")
require("blocks/drawer/spin")