//idk how to make this more compact
//power
require("blocks/generator/adv-steam");
require("blocks/generator/therm");
require("blocks/generator/clicker-gen");
require("blocks/generator/reactor")
//turrets
require("blocks/turret/cross-bow");
require("blocks/turret/salt-gun");
require("blocks/turret/silo");
require("blocks/turret/quake");
require("blocks/turret/dome-silo");
require("blocks/turret/minigun");
//crafter
require("blocks/crafter/spore-havester");
require("blocks/crafter/big-phase");
require("blocks/crafter/lab");
//defensive
require("blocks/defense/shootWall")
require("blocks/defense/laserNode")
//distribution
require("blocks/distribution/big-router")
require("blocks/distribution/conjoiner")
require("blocks/distribution/phase-bridge")
//drills
require("blocks/drill/phase-drill")
require("blocks/drill/gear-drill")
//other
require("blocks/misc/collector")
require("blocks/misc/cooler")
require("blocks/misc/salt-bomb")
require("blocks/misc/accelerator")
require("blocks/misc/healer")
//draw-based
require("blocks/drawer/spin")